# Creating the database
create database ecommerce;

# Connecting with the database
use ecommerce;

# 1. # Top 10 cities by  the number of customers
SELECT customer_city, COUNT(*) as customer_count
FROM customers
GROUP BY customer_city
ORDER BY customer_count DESC
LIMIT 10;

# 2. Count the number of orders placed in 2018
SELECT COUNT(order_id) AS orders_in_2018
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2018;

# 3. Find the total sales generated across product categories to identify top performing categories
SELECT 
    UPPER(products.product_category) AS category,
    ROUND(SUM(payments.payment_value), 2) AS sales
FROM products
JOIN order_items
    ON products.product_id = order_items.product_id
JOIN payments
    ON payments.order_id = order_items.order_id
WHERE products.product_category IS NOT NULL
GROUP BY category
ORDER BY sales DESC
LIMIT 10;

# 4. Calculate the percentage of orders that were paid in installments
SELECT 
ROUND(
    (SUM(CASE WHEN payment_installments > 1 THEN 1 ELSE 0 END) * 100.0) / COUNT(*),
2
) AS installment_percentage
FROM payments;

# 5. Count the number of customers from each state
SELECT customer_state, COUNT(customer_id) AS customer_count
FROM customers
GROUP BY customer_state;

# 6. Monthly ordertrend in 2018
SELECT 
    MONTHNAME(order_purchase_timestamp) AS month,
    COUNT(order_id) AS order_count
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2018
GROUP BY MONTH(order_purchase_timestamp), MONTHNAME(order_purchase_timestamp)
ORDER BY MONTH(order_purchase_timestamp);

# 7. Identify the cities with the highest average products purchased per order
WITH count_per_order AS (
    SELECT 
        orders.order_id,
        orders.customer_id,
        COUNT(order_items.order_id) AS product_count
    FROM orders
    JOIN order_items
        ON orders.order_id = order_items.order_id
    GROUP BY orders.order_id, orders.customer_id
)

SELECT 
    customers.customer_city,
    ROUND(AVG(count_per_order.product_count), 2) AS avg_products_per_order
FROM customers
JOIN count_per_order
    ON customers.customer_id = count_per_order.customer_id
GROUP BY customers.customer_city
ORDER BY avg_products_per_order DESC
LIMIT 10;

# 8. Calculate the percentage of total revenue contributed by each product category
SELECT 
    UPPER(products.product_category) AS category,
    ROUND(
        (SUM(payments.payment_value) / 
        (SELECT SUM(payment_value) FROM payments)) * 100,
    2) AS revenue_percentage
FROM products
JOIN order_items
    ON products.product_id = order_items.product_id
JOIN payments
    ON payments.order_id = order_items.order_id
WHERE products.product_category IS NOT NULL
GROUP BY category
ORDER BY revenue_percentage DESC
LIMIT 10;

# 9. Identify the correlation between product price and the number of tiems the product has been purchased
SELECT 
    seller_id,
    revenue,
    DENSE_RANK() OVER (ORDER BY revenue DESC) AS seller_rank
FROM (
    SELECT 
        order_items.seller_id,
        ROUND(SUM(payments.payment_value), 2) AS revenue
    FROM order_items
    JOIN payments
        ON order_items.order_id = payments.order_id
    GROUP BY order_items.seller_id
) AS seller_revenue
LIMIT 10;

# 10. Calculate the total revenue generated by each seller, and rank by revenue
SELECT 
    customer_id,
    order_purchase_timestamp,
    order_value,
    AVG(order_value) OVER (
        PARTITION BY customer_id
        ORDER BY order_purchase_timestamp
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS moving_avg
FROM (
    SELECT 
        orders.customer_id,
        orders.order_purchase_timestamp,
        payments.payment_value AS order_value
    FROM payments
    JOIN orders
        ON payments.order_id = orders.order_id
) AS customer_orders
LIMIT 100;

# 11. Track cumulative monthly sales across years to compare revenue growth patterns
SELECT 
    sales_year,
    sales_month,
    monthly_sales,
    SUM(monthly_sales) OVER (
        PARTITION BY sales_year
        ORDER BY sales_month
    ) AS cumulative_sales
FROM (
    SELECT 
        YEAR(orders.order_purchase_timestamp) AS sales_year,
        MONTH(orders.order_purchase_timestamp) AS sales_month,
        ROUND(SUM(payments.payment_value), 2) AS monthly_sales
    FROM orders
    JOIN payments
        ON orders.order_id = payments.order_id
    GROUP BY sales_year, sales_month
) AS monthly_sales_data;

# 12. Calculate the year-over-year-growth rate for total sales
with a as (select year(orders.order_purchase_timestamp) as years,
round(sum(payments.payment_value), 2) as payment from orders join payments 
on orders.order_id = payments.order_id
group by years order by years)

select years, ((payment - lag(payment, 1) over(order by years)) / lag(payment, 1) over(order by years)) * 100 from a;

# 13. Calculate the retention rate of customers, defined as thepercentage of customers who make another purchase within 6 months
with a as(select customers.customer_id,
min(orders.order_purchase_timestamp) first_order
from customers join orders
on customers.customer_id = orders.customer_id
group by customers.customer_id),
b as (select a.customer_id, count(distinct orders.order_purchase_timestamp)
from a join orders
on orders.customer_id = a.customer_id
and orders.order_purchase_timestamp > first_order
and orders.order_purchase_timestamp < date_add(first_order, interval 6 month)
group by a.customer_id)
select 100 * (count(distinct a.customer_id) / count(distinct b.customer_id))
from a left join b
on a.customer_id = b.customer_id;

# 14. Identify the top 3 customers who spent the most money in each year
SELECT 
    order_year,
    customer_id,
    total_spent,
    customer_rank
FROM (
    SELECT 
        YEAR(orders.order_purchase_timestamp) AS order_year,
        orders.customer_id,
        ROUND(SUM(payments.payment_value), 2) AS total_spent,
        DENSE_RANK() OVER (
            PARTITION BY YEAR(orders.order_purchase_timestamp)
            ORDER BY SUM(payments.payment_value) DESC
        ) AS customer_rank
    FROM orders
    JOIN payments
        ON payments.order_id = orders.order_id
    GROUP BY YEAR(orders.order_purchase_timestamp), orders.customer_id
) AS ranked_customers
WHERE customer_rank <= 3
ORDER BY order_year, customer_rank;  